### ISSUE TITLE
server fails to start - missing json files

### ISSUE THREAD

**Issue by Nordicdesign** [david-maus/PC2-ServerManager-GUI#1]
Hey, not sure what's the state of this tool, but looks very interesting, way clearer than the other PCars2 GUI I've found so far. Problem is that I can't start the server, 2 json files are missing.

![image](https://user-images.githubusercontent.com/4093514/56851210-4894ae80-6904-11e9-8c87-4cddb681a38e.png)

Now I may be doing something wrong, as I don't fully understand how to use it. Steps I followed:

1. Launch the software
2. Select an empty folder add the top.
3. Enter my steam details
4. Give a servername, click Add Server

# On server settings
5. Choose a server name, set practice, max players.
6. Choose track
7. Click start server

And at that point the console appears for half second and closes. Had to record a video to actually view the error (image above).

Cheers,
Alex

**Comment by david-maus** [comment]
Hi,

sorry for the massive delay but i dont play PC2 since a year :)

Maybe there is something changed in the lua server configs? I have tested it on my server and it is running so far... Dont know what is causing the problem on your machine. If i remember correctly the error message about the missing .json files is not a problem, the serverwrapper is copying the files from the inc directory. The data files are generated on the fly from the server itself i think.

Maybe you can give some details about your machine (Windows Version, Language, Username etc.).

Maybe we can make a remote session an i can look into it.

**Comment by Nordicdesign** [comment]
hey no worries, I too decided to stop trying hosting races on PC2 as their dedi server doesn't do what I want. Moved to AC now :D Thanks for the reply anyway!
